### ISSUE TITLE
F48.0 Dungeon Master Rolle abgeben

### ISSUE THREAD

**Issue by Endunry** [MUD-Game/HouseOfMUD#18]
### Frontend

- [x] Möglichkeit bieten die Rolle zu übergeben an einen gezielten Nutzer

### Backend

- [x] Die Übergabe im Backend umsetzen
- [x] bei jedem Start wird Creator zum Dungeon Master
- [x] Rolle kann dann weitergegeben werden
- [x] Beim Neustart wird Creator wieder zum Dungeon Master

**Comment by Raqhael** [comment]
Frontend sollte alles soweit stehen
