### ISSUE TITLE
[Bug]: Blacklist wird resettet wenn Dungeon bearbeitet wird

### ISSUE THREAD

**Issue by FabiKl** [MUD-Game/HouseOfMUD#237]
### What happened?

Blacklist wird resettet wenn Dungeon bearbeitet wird

### Location

Supervisor

**Comment by Raqhael** [comment]
![image](https://user-images.githubusercontent.com/57198743/168428473-c6d43b13-a0a3-478c-acfa-fe1101819733.png)

well well well
