### ISSUE TITLE
[Bug]: Charaktername(max 50 Zeichen) nimmt unendlich zeichen

### ISSUE THREAD

**Issue by Lucs77777** [MUD-Game/HouseOfMUD#245]
### What happened?

The charactename can have more letters than allowed
Gilt auch für Name/Beschreibung eines Raumes

![grafik](https://user-images.githubusercontent.com/85731411/168427503-cb71ecec-b8da-4376-ad52-ed860d8e60d9.png)

### Location

Frontend

**Comment by Raqhael** [comment]
fix with cd6be365d66de1b86bee2409922e1243fdb99671
