### ISSUE TITLE
[Bug]: Stringerkennung bei z.b addroomitem

### ISSUE THREAD

**Issue by Lucs77777** [MUD-Game/HouseOfMUD#247]
### What happened?

Wenn ein Raum/Item ein Leerzeichen hat, wird es falsch erkannt
![grafik](https://user-images.githubusercontent.com/85731411/168428443-d2941cab-e9cf-425d-bd9c-0f1af569bc06.png)

### Location

Frontend

**Comment by Raqhael** [comment]
Ups, der Standard Start Raum name kann noch leerzeichen haben, muss ich anpassen

**Comment by Raqhael** [comment]
Alte Dungeons die halt noch leerzeichen im Namen haben, müssen gelöscht werden
