### ISSUE TITLE
[Bug]: Leere Strings können beim Dungeon Master in die Queue gelegt werden

### ISSUE THREAD

**Issue by Lucs77777** [MUD-Game/HouseOfMUD#249]
### What happened?

Falsche Commands gehen da auch rein
Vielleicht sollte man den Command checken nach Funktionalität, bevor er da rein geht ?

![grafik](https://user-images.githubusercontent.com/85731411/168429129-2ab08503-ec9f-4c92-bf36-002622fe6077.png)

### Location

Frontend

**Comment by Raqhael** [comment]
falsche Commands checken wäre zu umständlich, das soll letzendlich ja nur eine Anzahl an commands auf einmal ausführen. Aber machen nen check rein das es keine leeren strings rein pack
